// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASEUgsC1n67juPgioTEReyWSZBve2OH5w',
    appId: '1:409439944456:web:6aa2d17a4f0afefebcb6bd',
    messagingSenderId: '409439944456',
    projectId: 'hellsing-undead-or-applive',
    authDomain: 'hellsing-undead-or-applive.firebaseapp.com',
    storageBucket: 'hellsing-undead-or-applive.firebasestorage.app',
    measurementId: 'G-NMLVM4JBTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzSaC66DBsTpufU-PFMFNT5QsFyxDgV5A',
    appId: '1:409439944456:android:6de210c4387fcc30bcb6bd',
    messagingSenderId: '409439944456',
    projectId: 'hellsing-undead-or-applive',
    storageBucket: 'hellsing-undead-or-applive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSpc4OkVrX14P1m9WWQgWJC6KWA9CtqzY',
    appId: '1:409439944456:ios:14a4fd9b0008f292bcb6bd',
    messagingSenderId: '409439944456',
    projectId: 'hellsing-undead-or-applive',
    storageBucket: 'hellsing-undead-or-applive.firebasestorage.app',
    iosBundleId: 'com.example.hellsingUndeadOrApplive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSpc4OkVrX14P1m9WWQgWJC6KWA9CtqzY',
    appId: '1:409439944456:ios:14a4fd9b0008f292bcb6bd',
    messagingSenderId: '409439944456',
    projectId: 'hellsing-undead-or-applive',
    storageBucket: 'hellsing-undead-or-applive.firebasestorage.app',
    iosBundleId: 'com.example.hellsingUndeadOrApplive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASEUgsC1n67juPgioTEReyWSZBve2OH5w',
    appId: '1:409439944456:web:e100820fa1bf325dbcb6bd',
    messagingSenderId: '409439944456',
    projectId: 'hellsing-undead-or-applive',
    authDomain: 'hellsing-undead-or-applive.firebaseapp.com',
    storageBucket: 'hellsing-undead-or-applive.firebasestorage.app',
    measurementId: 'G-1KC338Z8LS',
  );

}