import '../book_index.dart';
import '../book_page.dart';

const sectionClassesCommunes = RawSection(
  id: 'classes_communes',
  title: 'Classes communes',
  pages: [
    // ---- Fusiller ----------------------------------------------------------
    ClassSheetPage(
      id: 'classe_fusiller',
      sectionId: 'classes_communes',
      title: 'Fusiller',
      className: 'Fusiller',
      classCategory: 'Classes communes',
      quote: 'Dieu a créé tous les êtres rampant sur cette Terre, Samuel Colt les a rendus égaux.',
      classBonuses: ['/6 Fin Tireur', '/6 Réflexe', '/6 Vue Perçante'],
      equipment: [
        EquipmentSlot(label: 'Arme à Feu', detail: 'DX (Effet) Calibre Rechargement:x Bar[-/-/-/-/-/-] S.A'),
        EquipmentSlot(label: 'Arme à Feu', detail: 'DX (Effet) Calibre Rechargement:x Bar[-/-/-/-/-/-] S.A'),
        EquipmentSlot(label: 'Munitions', detail: '3 emplacements'),
      ],
      affinities: ['Armes à Feu'],
      munitionSlots: 3,
      skillFormula: 'Physique/20 compétences — PE = Physique/10',
      freeSkills: [
        'Double Tir (-2PE, tire avec deux armes sur la même cible, -10% par tir)',
      ],
      accessibleSkills: [
        'Tir de Suppression (-1PE, force à couvert, +20% par tir successif)',
        'Tir de Sommation (-1PE, gratuit hors combat, Mod 15% menace)',
        'Tir réflexe (-2PE, Mod -5%, tir lors de la défense)',
        'Tir Rapide (-2PE, Mod -5%, peut agir en premier)',
        'Tir Chirurgical (-2PE, zone précise sans malus de 20%)',
        'Recharge Rapide (-2PE, ignore le temps de rechargement)',
        'Tir au Jugé (-2PE, tire sans perdre la couverture)',
        'Tir assuré (-3PE, 1 tour d\'attente, +30%, Mod 15%)',
        'Tir d\'interruption (-3PE, agit durant le tour ennemi) (L)',
        'Ricochet (-3PE, tire en ricochet avec Mod 10%)',
        'Rafales (-4PE, enchaîne les tirs jusqu\'à raté ou chargeur vide)',
        'Pluie de Balles (-5PE, cibles illimitées, épuise les munitions) (L)',
      ],
    ),

    // ---- Artificier --------------------------------------------------------
    ClassSheetPage(
      id: 'classe_artificier',
      sectionId: 'classes_communes',
      title: 'Artificier',
      className: 'Artificier',
      classCategory: 'Classes communes',
      quote: 'La poudre, c\'est la solution universelle. Faut juste en mettre la bonne quantité.',
      classBonuses: ['/6 Lancer', '/6 Sapeur', '/6 Artisanat'],
      equipment: [
        EquipmentSlot(label: 'Arme à Feu', detail: 'DX (Effet) Calibre Rechargement:x Bar[-/-/-/-/-/-] S.A'),
        EquipmentSlot(label: 'Kit', detail: 'Kit de Création d\'Explosifs'),
        EquipmentSlot(label: 'Munitions', detail: '2 emplacements dont 1 dédié aux Explosifs (6 max)'),
      ],
      affinities: ['Armes à Feu', 'Explosifs'],
      munitionSlots: 2,
      skillFormula: 'Mental/20 compétences — PE = Physique/10',
      freeSkills: [
        'Déminage (-1PE en combat, désamorce un explosif)',
      ],
      accessibleSkills: [
        'Jonglage Explosif (-1PE par bombe, lance un nombre illimité de bombes)',
        'Plan de Démolition (planifie la destruction d\'une structure avec le minimum d\'explosifs)',
        'Grenade à Main (2PE Fab., D6 dégâts, Mod 10% Lancer)',
        'Bâton de Dynamite (2PE Fab., D8 dégâts, peut être lancé ou posé)',
        'Cocktail Molotov (1PE Fab., D4 dégâts, Effet Incendiaire)',
        'Bombe Tuyau (3PE Fab., D10 dégâts, détonateur)',
        'Mine (3PE Fab., D12 dégâts, piège)',
        'Charge de Démolition (6PE Fab., 2D20, dégâts doublés structures, 3 emplacements)',
        'Bombe à Clous (4PE Fab., 3D4 dégâts)',
        'Bombe Incendiaire (5PE Fab., 2D10 dégâts, Effet Incendiaire, 2 emplacements)',
        'Flasque de Nitroglycérine (1PE Fab., D8 dégâts, explose à l\'impact)',
        'Bombe Fumigène (1PE Fab., nuage de fumée)',
        'Bombe Aveuglante (1PE Fab., flash lumineux)',
        'Bombe Sonore (1PE Fab., détonation désorientante)',
      ],
    ),

    // ---- Bretteur ----------------------------------------------------------
    ClassSheetPage(
      id: 'classe_bretteur',
      sectionId: 'classes_communes',
      title: 'Bretteur',
      className: 'Bretteur',
      classCategory: 'Classes communes',
      quote: 'La plupart des créatures de cette Terre restent sensibles à une chose : une bonne toise d\'acier en travers du corps.',
      classBonuses: ['/6 Escrime', '/6 Garde', '/6 Premier soin'],
      equipment: [
        EquipmentSlot(label: 'Arme blanche', detail: 'Coupe: DX (Effet) Estoc: DX'),
        EquipmentSlot(label: 'Arme blanche', detail: 'Coupe: DX (Effet) Estoc: DX'),
        EquipmentSlot(label: 'Munitions', detail: '0 emplacement'),
      ],
      affinities: ['Armes blanches à une main', 'Armes blanches à deux mains'],
      munitionSlots: 0,
      skillFormula: 'Physique/20 compétences — PE = Physique/10',
      freeSkills: [
        'Enchaînement (-1PE, si une première attaque touche, lance une seconde sur la même cible)',
      ],
      accessibleSkills: [
        '— Arme à une main —',
        'Parade Fluide (-1PE, Mod -5%, attaque d\'opportunité après parade réussie)',
        'Passe d\'armes (-2PE, désarme l\'adversaire en cas de réussite)',
        'Pugilat (-2PE, attaque désarmée D4 contondants)',
        'Riposte (-2PE, attaque d\'opportunité après parade ou blessure, -2 dégâts)',
        'Estoc précis (-2PE, zone précise Mod 10% sans malus)',
        'Fente (-3PE, attaque en premier une cible à portée, +2 dégâts) (L)',
        'Attaque ambidextre (-3PE, attaque avec deux armes)',
        'Feinte (-3PE, ignore l\'action défensive de la cible) (L)',
        'Coupe-Jarret (-4PE, Effet Saignement Aggravé)',
        'Danse de Lame/d\'Estoc (-6PE, -20% parade adverse, 5 attaques) (L)',
        '— Arme à deux mains —',
        'Garde Solide (-1PE/tour, Mod +20% parade)',
        'Étourdissement (-1PE, dégâts infligés aux PE)',
        'Brise-garde (-2PE, passe malgré la parade, -3 dégâts)',
        'Grande Taille (-3PE, Mod -10%, 2x dés dégâts, cibles multiples) (L)',
        'Charge (-3PE, attaque en premier sur cible à portée de déplacement)',
        'Feinte Lourde (-3PE, malus défense adverse de 40%)',
        'Démembrement (-4PE, sectionne un membre si dégâts > 6)',
        'Contre Mortel (-5PE, 3x dégâts sur parade réussie) (L)',
      ],
    ),

    // ---- Apothicaire -------------------------------------------------------
    ClassSheetPage(
      id: 'classe_apothicaire',
      sectionId: 'classes_communes',
      title: 'Apothicaire',
      className: 'Apothicaire',
      classCategory: 'Classes communes',
      quote: 'Les plantes sont des choses étranges et mystérieuses, elles peuvent aussi bien vous sauver la vie que vous mener à la mort. Un thé ?',
      classBonuses: ['/6 Soin', '/6 Herbologie', '/6 Chimie'],
      equipment: [
        EquipmentSlot(label: 'Arme blanche', detail: 'Coupe: D4 max (Effet) Estoc: D4 max'),
        EquipmentSlot(label: 'Kit', detail: 'Kit de Pharmacie + Matériel d\'Analyses Chimiques'),
        EquipmentSlot(label: 'Munitions', detail: '1 emplacement dédié aux Herbes (6 max)'),
      ],
      affinities: ['Armes blanches à une main'],
      munitionSlots: 1,
      skillFormula: 'Mental/20 compétences — PE = Physique/10',
      freeSkills: [
        'Identification (au calme, analyse une substance et détermine sa nature)',
        'Mithridatisation (immunité à la plupart des poisons)',
      ],
      accessibleSkills: [
        'Poudre urticante (-1PE Fab., -40% à la cible pour le prochain tour)',
        'Cataplasme Curatif (-1PE Fab., D4+2 PV, 2 tours d\'immobilité)',
        'Antidote (-1PE Fab., nécessite un échantillon, soigne ce poison)',
        'Graine de rage (-2PE Fab., -1PV/tour, rage D4 tours, +2 dégâts CàC)',
        'Huile Inflammable (-2PE Fab., Effet Incendiaire à une arme D6 tours)',
        'Sang noir (-3PE Fab., empoisonne le vampire buveur, protège du vampirisme)',
        'Poudre Somnifère (-2PE Fab., 4/6 chance d\'endormir, -20% D4 tours)',
        'Tue-Loup (-3PE Fab., Effet Argent à une arme D6 tours)',
        'Drogue d\'Hypersensibilité (-4PE Fab., -2PV, +30% perception, Mod 10% visée, 2D4 tours)',
        'Cercle de Protection Botanique (-4PE Fab., empêche les Midians d\'entrer, 3 personnes)',
        'Laudanum (-4PE Fab., supprime la douleur, +1PV/tour D4 tours)',
        'Chloroforme (-5PE Fab., endort la cible au contact)',
      ],
    ),

    // ---- Chirurgien --------------------------------------------------------
    ClassSheetPage(
      id: 'classe_chirurgien',
      sectionId: 'classes_communes',
      title: 'Chirurgien',
      className: 'Chirurgien',
      classCategory: 'Classes communes',
      quote: 'Si on part chasser des créatures légendaires sans aide médicale, ce n\'est plus de la stupidité mais du darwinisme.',
      classBonuses: ['/6 Chirurgie', '/6 Anatomie', '/6 Diagnostic'],
      equipment: [
        EquipmentSlot(label: 'Arme blanche', detail: 'Coupe: D4 max (Effet) Estoc: D4 max'),
        EquipmentSlot(label: 'Kit', detail: 'Kit de Chirurgie + Matériel d\'Analyses Médicales'),
        EquipmentSlot(label: 'Munitions', detail: '0 emplacement'),
      ],
      affinities: ['Armes blanches à une main'],
      munitionSlots: 0,
      skillFormula: 'Mental/20 compétences — PE = Physique/10',
      freeSkills: [
        'Autopsie (au calme, détermine les circonstances de la mort d\'une créature)',
      ],
      accessibleSkills: [
        'Transfusion (gratuit, protège du vampirisme, -2PE au donneur)',
        'Dissection (au calme, détermine la nature et les capacités d\'une créature)',
        'Analyse d\'échantillon (au calme, détermine l\'origine d\'échantillons biologiques)',
        'Sutures (-1PE, +1PV/tour pendant D6 tours)',
        'Extraction de Balle (-1PE, réduit les dégâts d\'une blessure par balle à 1)',
        'Bandages Hémostatiques (-1PE, +3PV temporaire, arrête les saignements)',
        'Analyse anatomique (-2PE, déduit la position des organes vitaux)',
        'Stimulation stéroïdienne (-2PE, +2 dégâts CàC pendant 2 tours)',
        'Réduction de Fracture (-2PE, membre fracturé douloureux mais utilisable)',
        'Opération Chirurgicale (-3PE, réduit dégâts à 1, 1 tour par 2PV) (L)',
        'Dislocation (-3PE, disloque un membre humanorde au contact)',
        'Stabilisation (-4PE, empêche la mort)',
        'Chirurgie de la dernière chance (-6PE, D6 tours, sauve un personnage à 2PV) (L)',
      ],
    ),

    // ---- Pisteur -----------------------------------------------------------
    ClassSheetPage(
      id: 'classe_pisteur',
      sectionId: 'classes_communes',
      title: 'Pisteur',
      className: 'Pisteur',
      classCategory: 'Classes communes',
      quote: 'Vous savez, c\'est bien beau de savoir écharper un vampire, si vous êtes incapable de le dénicher…',
      classBonuses: ['/6 Poursuite', '/6 Sens Aûtés', '/6 Traque'],
      equipment: [
        EquipmentSlot(label: 'Arme', detail: 'Arme à Feu DX S.A OU Arme d\'Archerie DX Rechargement:x'),
        EquipmentSlot(label: 'Munitions', detail: '1 emplacement'),
      ],
      affinities: ['Armes d\'Archerie', 'Armes à Feu'],
      munitionSlots: 1,
      skillFormula: 'Physique/20 compétences — PE = Physique/10',
      freeSkills: [
        'Cible Favorite (espèce spécifique, Mod 10% recherche et combat contre cette créature)',
      ],
      accessibleSkills: [
        'Art du déplacement (ignore les malus de déplacement d\'un environnement)',
        'Maître-Chien (chien dressé, D4 d\'attaque)',
        'Piste (-1PM, suit une piste indiscernable normalement)',
        'Intuition (-2PM, devine la prochaine action de la cible)',
        'Investigation totale (-3PM, repère rapidement tous les indices d\'un lieu)',
        'Esprit de la Bête (-4PM, reconstitue le parcours ou les actions d\'une cible identifiée)',
        'Dissimulation (-1PE/tour, indétectable sauf critique, immobile)',
        'Position de tir (-1PE/tour, Mod 10% aux jets de tir)',
        'Embuscade (-1PE, Mod 15% à la prochaine action si non repéré)',
        'Poursuite (-2PE, interrompt la fuite d\'une cible durant son tour)',
        'Tension réflexe (-2PE, esquive avec Mod 10%)',
        'Prévision des trajectoires d\'esquive (-3PE, touche même si la cible esquive)',
        'Instinct de Chasseur (-5PE, repère toutes les entités physiques D8 tours)',
      ],
    ),

    // ---- Assassin ----------------------------------------------------------
    ClassSheetPage(
      id: 'classe_assassin',
      sectionId: 'classes_communes',
      title: 'Assassin',
      className: 'Assassin',
      classCategory: 'Classes communes',
      quote: 'Travailler et se battre dans l\'ombre et au secret ? Je connais oui…',
      classBonuses: ['/6 Furtivité', '/6 Lancer', '/6 Coup en traître'],
      equipment: [
        EquipmentSlot(label: 'Arme', detail: 'Arme blanche D6 max OU Arme D4 max + Arme de lancer Nbr:5'),
        EquipmentSlot(label: 'Munitions', detail: '0 emplacement'),
      ],
      affinities: ['Armes blanches à une main', 'Armes de lancer'],
      munitionSlots: 0,
      skillFormula: 'Physique/20 compétences — PE = Physique/10',
      freeSkills: [
        'Coup en traître (-2PE, si non repéré, lance 2 fois les dégâts) (L)',
      ],
      accessibleSkills: [
        'Effacement (-1PE, Mod 10% à l\'esquive)',
        'Jongleur de couteaux (-1PE par lancer, lancers illimités dans cette action)',
        'Attaque ambidextre (-2PE, attaque avec deux armes)',
        'Disparition (-2PE, disparaît aux yeux de la cible si son attention est ailleurs)',
        'Attaque Précise (-2PE, attaque une zone précise en ignorant les malus)',
        'Pas de l\'ombre (-2PE, -60% au jet de perception adverse)',
        'Camouflage (-3PE/tour, déplacement indétectable sauf critique)',
        'Coup Vicieux (-3PE, Effet Saignement Aggravé)',
        'Coup critique (-3PE, dé supplémentaire, relancé si valeur max) (L)',
        'Assassinat (-3PE, 4x dégâts si attaque dans le dos non repéré) (L)',
        'Épinglage (-4PE, 5 armes de lancer épinglent la cible contre une surface)',
      ],
    ),
  ],
);
