import 'package:hellsing_undead_or_applive/domain/models.dart';

enum Calibre { 
  empty, herb, bolt, throwable, point22, point22LR, point32Rimfire,
  point36, point38d10v4mm , point40LongRifle, point41, point41and32,
  point41Comet, point41LongColt, point41MoonSlayer, point426SilverDevil,
  point44Henry, point44Magnum, point44Winchester, point45, bore8, gauge10,
  point45Remington, point45Sharps, point454Casul, point47Round, gauge12,
  point51Enfield, point52R, point56Meteor, point57Enfield, point66PaterNoster,
}

enum Effect { 
  none(aggraved: false),
  blessed(aggraved: false), blessedAggr(aggraved: true),
  holy(aggraved: false),
  silver(aggraved: false), silverAggr(aggraved: true),
  mercury(aggraved: false), mercuryAggr(aggraved: true),
  piercing(aggraved: false), piercingAggr(aggraved: true),
  incendiary(aggraved: false), incendiaryAggr(aggraved: true),
  burning(aggraved: false), burningAggr(aggraved: true), 
  bleed(aggraved: false), bleedAggr(aggraved: true);
  
  final bool aggraved;
  const Effect({required this.aggraved});
}

enum Firing { none, sA, dA, multiple, semA, separedTrigger, mLev, mVer,}

enum SubAffinities { 
  smallOneHandBlade, 
  bigOneHandBlade, 
  smallTwoHandBlade, 
  bigTwoHandBlade, 
  bow, 
  throwable, 
  smallHandgun, 
  bigHandgun, 
  dispersion,
  smallRifle, 
  bigRifle,
}


/////////////////////////////
//                         //
//    WEAPON MODIF LIST    //
//                         //
/////////////////////////////


class WeaponModifList {
  List<WeaponModif> allWeaponModifs = [
    WeaponModif(
      name: "Acier Béni pour petites lames", 
      legend: "Garantie résistante au péché.", 
      feature: "Confère l'effet Bénie à l'arme.", 
      price: 100, 
      type: SubAffinities.smallOneHandBlade,
      effect: Effect.blessed,
    ),
    WeaponModif(
      name: "Fil d'Argent pour petites lames", 
      legend: "Plus efficace que de l'argenterie.", 
      feature: "Confère l'effet Argent à l'arme.", 
      damage: "-1 à l'estoc",
      price: 400, 
      type: SubAffinities.smallOneHandBlade,
      effect: Effect.silver,
    ),
    WeaponModif(
      name: "Gouttières à poisons", 
      legend: "La touche finale à un bon assassinat.", 
      feature: "Permet d'empoisonner la lame.", 
      price: 30, 
      type: SubAffinities.smallOneHandBlade,
    ),
    WeaponModif(
      name: "Acier Béni", 
      legend: "Dans la plus pure tradition des croisades.", 
      feature: "Confère l'effet Bénie à l'arme.", 
      price: 400, 
      type: SubAffinities.bigOneHandBlade,
      effect: Effect.blessed,
    ),
    WeaponModif(
      name: "Fil d'Argent", 
      legend: "Le meilleur allié du chasseur.", 
      feature: "Confère l'effet Argent à l'arme.", 
      price: 1000, 
      type: SubAffinities.bigOneHandBlade,
      effect: Effect.silver,
    ),
    WeaponModif(
      name: "Acier Béni", 
      legend: "Trempée dans un bénitier.", 
      feature: "Confère l'effet Bénie à l'arme.", 
      price: 500, 
      type: SubAffinities.smallTwoHandBlade,
      effect: Effect.blessed,
    ),
    WeaponModif(
      name: "Fil d'Argent", 
      legend: "Un tranchant riche et généreux.", 
      feature: "Confère l'effet Argent à l'arme.", 
      price: 1300, 
      type: SubAffinities.smallTwoHandBlade,
      effect: Effect.silver,
    ),
    WeaponModif(
      name: "Acier Béni", 
      legend: "Et l’Éternel vit que cela était bon.", 
      feature: "Confère l'effet Bénie à l'arme.", 
      price: 600, 
      type: SubAffinities.bigTwoHandBlade,
      effect: Effect.blessed,
    ),
    WeaponModif(
      name: "Fil d'Argent", 
      legend: "Pourquoi s'arrêter à l'acier ?", 
      feature: "Confère l'effet Argent à l'arme.", 
      price: 1500, 
      type: SubAffinities.bigTwoHandBlade,
      effect: Effect.silver,
    ),
    WeaponModif(
      name: "Second arc", 
      legend: "Au cas ou le premier casse.", 
      feature: "Permet un second tir avant de devoir recharger", 
      price: 600, 
      type: SubAffinities.bow,
    ),
    WeaponModif(
      name: "Rechargement Mécanique", 
      legend: "Les avantages de la révolution industrielle.", 
      feature: "Réduit de moitié le temps de rechargement", 
      price: 1000, 
      type: SubAffinities.bow,
    ),
    WeaponModif(
      name: "Lunette", 
      legend: "C'est pour mieux te voir mon enfant.", 
      feature: "Évite les malus liés à la longue distance.", 
      price: 300, 
      type: SubAffinities.bow,
    ),
    WeaponModif(
      name: "Bipied", 
      legend: "Pour les mains tremblantes.", 
      feature: "Bonus à la visée depuis un poste de tir.", 
      price: 200, 
      type: SubAffinities.bow,
    ),
    WeaponModif(
      name: "Acier Béni", 
      legend: "La grâce divine en livraison express.", 
      feature: "Confère l'effet Bénie à l'arme.", 
      price: 100, 
      type: SubAffinities.throwable,
    ),
    WeaponModif(
      name: "Fil d'Argent", 
      legend: "Pour tuer les monstres à coups d'argenterie.", 
      feature: "Confère l'effet Argent à l'arme.", 
      price: 300, 
      type: SubAffinities.throwable,
    ),
    WeaponModif(
      name: "Gouttières à poisons", 
      legend: "Pourquoi s'en priver ?", 
      feature: "Permet d'empoisonner la lame.", 
      price: 50, 
      type: SubAffinities.throwable,
    ),
    WeaponModif(
      name: "Canon Allongé pour armes de poing légères", 
      legend: "Plus c'est long, plus c'est bon.", 
      feature: "Evite les malus liés à la longue distance.", 
      price: 1000, 
      type: SubAffinities.smallHandgun,
    ),
    WeaponModif(
      name: "Viseur amélioré pour armes de poing", 
      legend: "Un canon, ça se doit d'avoir des formes.", 
      feature: "Évite les malus en cas de tir en position instable.", 
      price: 800, 
      type: SubAffinities.smallHandgun,
    ),
    WeaponModif(
      name: "Changement de magasin pour armes légères", 
      legend: "Parfois, six balles ne suffisent pas.", 
      feature: "Augmentation ou diminution du Magasin ou Barillet.", 
      price: 1500, 
      type: SubAffinities.smallHandgun,
    ),
    WeaponModif(
      name: "Canon Rayé pour armes de poing de gros calibre", 
      legend: "Rainuré pour une éjection plus précise.", 
      feature: "Évite les malus liés à la longue distance.", 
      price: 1200, 
      type: SubAffinities.bigHandgun,
    ),
    WeaponModif(
      name: "Viseur amélioré pour armes de poing de gros calibre", 
      legend: "Le gros calibre, c'est bien. Toucher c'est mieux.", 
      feature: "Évite les malus liés à l'instabilité.", 
      price: 800, 
      type: SubAffinities.bigHandgun,
    ),
    WeaponModif(
      name: "Changement de magasin pour armes de poing de gros calibre", 
      legend: "La balle qui fera la différence.", 
      feature: "Augmentation ou diminution du magasin.", 
      price: 1700, 
      type: SubAffinities.bigHandgun,
    ),
    WeaponModif(
      name: "Canon Supplémentaire", 
      legend: "Au cas ou le premier explose.", 
      feature: "Ajoute un tir.", 
      price: 800, 
      type: SubAffinities.dispersion,
    ),
    WeaponModif(
      name: "Gâchette séparée", 
      legend: "Quand on manie un canon, il faut avoir le choix.", 
      feature: "Permet de choisir le ou les canons faisant feu.", 
      price: 500, 
      type: SubAffinities.dispersion,
      firing: Firing.separedTrigger,
    ),
    WeaponModif(
      name: "Canon Allongé pour Fusil", 
      legend: "Quand on veut toucher une cible lointaine, on rapproche le fusil de quelques pouces.", 
      feature: "Évite des malus liés à la longue distance.", 
      price: 1400, 
      type: SubAffinities.smallRifle,
    ),
    WeaponModif(
      name: "Mire et viseur améliorée pour Fusil", 
      legend: "Quand on veut faire mouche au sens littéral.", 
      feature: "Évite des malus liés à l'instabilité à courte distance.", 
      price: 1300, 
      type: SubAffinities.smallRifle,
    ),
    WeaponModif(
      name: "Bipied pour Fusil", 
      legend: "Pratique pour un gibier rapide.", 
      feature: "Bonus a la visée depuis un poste de tir.", 
      price: 300, 
      type: SubAffinities.smallRifle,
    ),
    WeaponModif(
      name: "Baïonnette", 
      legend: "La Garde meurt mais ne se rend pas !", 
      feature: "Permet d'utiliser son fusil comme une lance.",
      damage: "Estoc D4", 
      price: 300, 
      type: SubAffinities.smallRifle,
    ),
    WeaponModif(
      name: "Lunette", 
      legend: "Étrangement, à une certaine distance, les cibles baissent leur garde.", 
      feature: "Évite des malus liés à la longue distance et augmente la portée pratique.", 
      price: 1600, 
      type: SubAffinities.bigRifle,
    ),
    WeaponModif(
      name: "Suppresseur", 
      legend: "Le tir de précision repose sur un atout fondamental : la discrétion.", 
      feature: "Réduit le bruit et l'éclat du coup de feu.", 
      price: 1000, 
      type: SubAffinities.bigRifle,
    ),
    WeaponModif(
      name: "Bipied pour Carabines", 
      legend: "Quitte à attendre, autant le faire confortablement.", 
      feature: "Bonus a la visée depuis un poste de tir.", 
      price: 300, 
      type: SubAffinities.bigRifle,
    ),
  ];

  ////////////////////////////////////
  //                                //
  // Fonction utiles pour les armes //
  //                                //
  ////////////////////////////////////

  List<WeaponModif> getWeaponListBySubtype(SubAffinities subType) {
    List<WeaponModif> res = [];

    for (var weaponModif in allWeaponModifs) {
      if (weaponModif.type == subType) {
        res.add(weaponModif);
      }
    }

    return res;
  }
}


///////////////////////
//                   //
//    WEAPON LIST    //
//                   //
///////////////////////


class WeaponsList {
  List<Weapon> allWeapons = [
    
    // Arme à une main 1
    
    Weapon(
      id: 0, 
      name: "Pieu en bois", 
      legend: "Un classique à usage unique, toujours efficace.", 
      damage: "Coupe : 0, Estoc : D4", 
      feature: "Reste en place et empêche la régénération.", 
      price: 5, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.smallOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 1, 
      name: "Pieu d'acier barbelé", 
      legend: "On n'arrête pas le progrès.", 
      damage: "Coupe : 0, Estoc : D4", 
      feature: "Reste en place et inflige D4 si retiré.", 
      price: 15, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.smallOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 2, 
      name: "Surin", 
      legend: "La base de l'escrime du prisonnier.", 
      damage: "Coupe : D2, Estoc : D4", 
      feature: "Casse Facilement.", 
      price: 20, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.smallOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 3, 
      name: "Poignard", 
      legend: "L'arme qui a le plus changé l'histoire.", 
      damage: "Coupe : D2, Estoc : D4", 
      feature: "", 
      price: 50, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.smallOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: true,
    ),
    Weapon(
      id: 4, 
      name: "Dague", 
      legend: "Plus forte que la Plume.", 
      damage: "Coupe : D4, Estoc : D4", 
      feature: "", 
      price: 60, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.smallOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 5, 
      name: "Hachette", 
      legend: "La brutalité en format de poche.", 
      damage: "Coupe : D4+1, Estoc : 0", 
      feature: "", 
      price: 80, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.smallOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 6, 
      name: "Baïonnette", 
      legend: "La garde meurt mais ne se rend pas.", 
      damage: "Coupe : 0, Estoc : D4", 
      feature: "Peut être équipé sur une arme à feu.", 
      price: 100, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.smallOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 7, 
      name: "Kukri", 
      legend: "Le pragmatisme Tibétain.", 
      damage: "Coupe : D4+1, Estoc : D2", 
      feature: "", 
      price: 160, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.smallOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 8, 
      name: "Poing Américain", 
      legend: "L'industrialisation à du bon.", 
      damage: "Atq désarmée : D4+1", 
      feature: "Inflige des dégâts contondant.", 
      price: 50, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.smallOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 9, 
      name: "Kriss", 
      legend: "Une lame rituelle des Philippines.", 
      damage: "Coupe : D4, Estoc : D4", 
      feature: "Inflige l'Effet Bénie et Saignement sur 4.", 
      price: 150, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.smallOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),

    // Armes à une main 2

    Weapon(
      id: 10, 
      name: "Matraque de Police", 
      legend: "Étudiée pour maintenir l'ordre.", 
      damage: "Coupe : D6, Estoc : D4", 
      feature: "Inflige des dégâts contusionnant.", 
      price: 80, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.bigOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: true,
    ),
    Weapon(
      id: 11, 
      name: "Masse à ailettes", 
      legend: "Toujours aussi efficaces qu'à l'époque.", 
      damage: "Coupe : D6, Estoc : D4", 
      feature: "Inflige des dégâts contusionnant permanents.", 
      price: 130, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.bigOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 12, 
      name: "Sabre d'infanterie", 
      legend: "Une lame digne d'un soldat : droite et rigide.", 
      damage: "Coupe : D6-1, Estoc : D6", 
      feature: "Facilement appris, facilement contré.", 
      price: 150, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.bigOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: true,
    ),
    Weapon(
      id: 13, 
      name: "Sabre de Cavalerie", 
      legend: "Sobre, courbe, efficace.", 
      damage: "Coupe : D6, Estoc : D6-1", 
      feature: "Facilement appris, facilement contré.", 
      price: 150, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.bigOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: true,
    ),
    Weapon(
      id: 14, 
      name: "Sabre Polonais", 
      legend: "Imprévisible, tel un noble d'Europe de l'Est.", 
      damage: "Coupe : D6, Estoc : D4", 
      feature: "Marque de noblesse en Europe de l'Est.", 
      price: 300, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.bigOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 15, 
      name: "Cimeterre oriental (Shamsheir)", 
      legend: "Les charmes de l'Orient.", 
      damage: "Coupe : D6, Estoc : D4", 
      feature: "Marque de noblesse au Proche-Orient.", 
      price: 300, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.bigOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 16, 
      name: "Pallasch Napoléonien", 
      legend: "Le fleuron de l’orgueil français.", 
      damage: "Coupe : D4, Estoc : D6", 
      feature: "Inflige l'Effet Perforant en Estoc.", 
      price: 450, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.bigOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 17, 
      name: "Rapière", 
      legend: "La précision et l'élégance d'un arme de duel.", 
      damage: "Coupe : D4, Estoc : D6", 
      feature: "+1 en Escrime lors de l'utilisation.", 
      price: 450, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.bigOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 18, 
      name: "Épée de Cour", 
      legend: "Convient aux combats comme aux réceptions.", 
      damage: "Coupe : 0, Estoc : D6-1", 
      feature: "Marque de noblesse en Europe de l'Ouest.", 
      price: 420, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.bigOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 19, 
      name: "Canne-épée", 
      legend: "La seule arme capable de vous aider à marcher.", 
      damage: "Coupe : D4, Estoc : D6", 
      feature: "Facilement dissimulable.", 
      price: 500,
      type: Affinities.oneHandBlade,
      subType: SubAffinities.bigOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 20, 
      name: "Épée à panier écossaise", 
      legend: "Parfaitement adaptée à « l'escrime » écossaise.", 
      damage: "Coupe : D6+1, Estoc : D6+1", 
      feature: "+1 en Garde lors de l'utilisation.", 
      price: 520, 
      type: Affinities.oneHandBlade,
      subType: SubAffinities.bigOneHandBlade,
      effect: [ Effect.none ],
      size: 1, 
      fire: false,
      startingWeapon: false,
    ),

    // Armes à deux mains 1

    Weapon(
      id: 21, 
      name: "Langmesser et Sabre Prussien", 
      legend: "La qualité Allemande.", 
      damage: "Coupe : D8, Estoc : D8", 
      feature: "Passe pour une arme de mercenaire prussien.", 
      price: 520, 
      type: Affinities.twoHandBlade,
      subType: SubAffinities.smallTwoHandBlade,
      effect: [ Effect.none ],
      size: 2,
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 22, 
      name: "Sabre Suisse", 
      legend: "Une arme assez neutre.", 
      damage: "Coupe : D8, Estoc : D6", 
      feature: "Facilement appris, facilement contré.", 
      price: 500, 
      type: Affinities.twoHandBlade,
      subType: SubAffinities.smallTwoHandBlade,
      effect: [ Effect.none ],
      size: 2,
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 23, 
      name: "Longue Épée Médiévale", 
      legend: "La nostalgie d'une époque révolue.", 
      damage: "Coupe : D8, Estoc : D8", 
      feature: "", 
      price: 550, 
      type: Affinities.twoHandBlade,
      subType: SubAffinities.smallTwoHandBlade,
      effect: [ Effect.none ],
      size: 2,
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 24, 
      name: "Hache de Bûcheron", 
      legend: "Pour couper un arbre, une chaise, un bras.", 
      damage: "Coupe : D8+2, Estoc : 0", 
      feature: "Malus de 10% Sauf Force Accrue.", 
      price: 200, 
      type: Affinities.twoHandBlade,
      subType: SubAffinities.smallTwoHandBlade,
      effect: [ Effect.none ],
      size: 2,
      fire: false,
      startingWeapon: true,
    ),
    Weapon(
      id: 25, 
      name: "Estoque", 
      legend: "Basiquement une lance avec une garde.", 
      damage: "Coupe : D4, Estoc : D8", 
      feature: "Inflige l'Effet Perforant en Estoc.", 
      price: 670, 
      type: Affinities.twoHandBlade,
      subType: SubAffinities.smallTwoHandBlade,
      effect: [ Effect.none ],
      size: 2,
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 26, 
      name: "Épée de la Palisse", 
      legend: "Une des 1000 meilleures lames d’Europe.", 
      damage: "Coupe : D8, Estoc : D6", 
      feature: "Ne peut être brisée par de l'Acier.", 
      price: 780,
      type: Affinities.twoHandBlade,
      subType: SubAffinities.smallTwoHandBlade,
      effect: [ Effect.none ],
      size: 2,
      fire: false,
      startingWeapon: false,
    ),

    // Armes à deux mains 2

    Weapon(
      id: 27, 
      name: "Claymore Écossaise", 
      legend: "Le symbole de l'argumentaire écossais.", 
      damage: "Coupe : D10, Estoc : D8", 
      feature: "Marque de noblesse en Écosse.", 
      price: 900,
      type: Affinities.twoHandBlade,
      subType: SubAffinities.bigTwoHandBlade,
      effect: [ Effect.none ],
      size: 2,
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 28, 
      name: "Zweihander Allemand", 
      legend: "Ne convient pas aux enfants.", 
      damage: "Coupe : D10, Estoc : D6", 
      feature: "Portée Accrue.", 
      price: 1000, 
      type: Affinities.twoHandBlade,
      subType: SubAffinities.bigTwoHandBlade,
      effect: [ Effect.none ],
      size: 2,
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 29, 
      name: "Hallebarde", 
      legend: "Le Raffinement Médiéval.", 
      damage: "Coupe : D8, Estoc : D6", 
      feature: "Portée Accrue.", 
      price: 800, 
      type: Affinities.twoHandBlade,
      subType: SubAffinities.bigTwoHandBlade,
      effect: [ Effect.none ],
      size: 2,
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 30, 
      name: "Épieu de Chasse", 
      legend: "Parfait pour achever une bête blessée.", 
      damage: "Coupe : D2, Estoc : D8", 
      feature: "Portée Accrue, ne peut transpercer.", 
      price: 600, 
      type: Affinities.twoHandBlade,
      subType: SubAffinities.bigTwoHandBlade,
      effect: [ Effect.none ],
      size: 2,
      fire: false,
      startingWeapon: true,
    ),
    Weapon(
      id: 31, 
      name: "Montante Espagnol", 
      legend: "Prépare toi à mourir si tu as tué son père.", 
      damage: "Coupe : D10, Estoc : D10", 
      feature: "Marque le Statut de Maître d'Arme.", 
      price: 1200, 
      type: Affinities.twoHandBlade,
      subType: SubAffinities.bigTwoHandBlade,
      effect: [ Effect.none ],
      size: 2,
      fire: false,
      startingWeapon: false,
    ),

    // Armes d'Archerie

    Weapon(
      id: 32, 
      name: "Arbalète légère à étrier", 
      legend: "Ou comment tirer à l'arc sans y passer sa vie.", 
      damage: "D6 par carreaux", 
      feature: "Portée effective : 35m", 
      price: 100, 
      type: Affinities.bow,
      subType: SubAffinities.bow,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.bolt,
      reload: 1,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: true,
    ),
    Weapon(
      id: 33, 
      name: "Arbalète pistolet", 
      legend: "Deux arbalètes valent mieux qu'une.", 
      damage: "D4 par carreaux", 
      feature: "Portée effective : 25m", 
      price: 70, 
      type: Affinities.bow,
      subType: SubAffinities.bow,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.bolt,
      reload: 0.5,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: false,
    ),
    Weapon(
      id: 34, 
      name: "Arbalète lourde à Cranequin", 
      legend: "L'arme des premiers tireurs d'élite.", 
      damage: "D8 par carreaux", 
      feature: "Portée effective : 60m", 
      price: 200, 
      type: Affinities.bow,
      subType: SubAffinities.bow,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.bolt,
      reload: 2,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: true,
    ),
    Weapon(
      id: 35, 
      name: "Arbalète légère à levier", 
      legend: "Pas une Winchester.", 
      damage: "D6 par carreaux", 
      feature: "Portée effective : 35m", 
      price: 160, 
      type: Affinities.bow,
      subType: SubAffinities.bow,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.bolt,
      reload: 0.5,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: false,
    ),
    Weapon(
      id: 36, 
      name: "Arbalète lourde à poulies", 
      legend: "Pour le gros gibier.", 
      damage: "D8 par carreaux", 
      feature: "Portée effective : 70m", 
      price: 350, 
      type: Affinities.bow,
      subType: SubAffinities.bow,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.bolt,
      reload: 1,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: false,
    ),
    Weapon(
      id: 37, 
      name: "Arbalète légère Chinoise « Chu Ko Nu »", 
      legend: "L'ancêtre spirituel des revolver, la précision en moins.", 
      damage: "D4 par carreaux", 
      feature: "Portée effective : 55m", 
      price: 450, 
      type: Affinities.bow,
      subType: SubAffinities.bow,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.bolt,
      reload: 2,
      magazineSize: 7,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: false,
    ),

    // Armes de Lancer

    Weapon(
      id: 38, 
      name: "Couteau de Lancer", 
      legend: "À planter avec le bout pointu.", 
      damage: "D2", 
      feature: "", 
      price: 20, 
      type: Affinities.throwable,
      subType: SubAffinities.throwable,
      effect: [ Effect.none ],
      size: 0.5, 
      fire: false,
      startingWeapon: true,
    ),
    Weapon(
      id: 39, 
      name: "Haches de lancer", 
      legend: "Pour le Bûcheronnage à distance.", 
      damage: "D4", 
      feature: "Rebonds imprévisibles.", 
      price: 40, 
      type: Affinities.throwable,
      subType: SubAffinities.throwable,
      effect: [ Effect.none ],
      size: 0.5, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 40, 
      name: "Chakram", 
      legend: "Simple et Tranchant. Le pragmatisme à l'indienne.", 
      damage: "D4", 
      feature: "Reviens dans la main si le jet d'attaque est inesquivable.", 
      price: 60, 
      type: Affinities.throwable,
      subType: SubAffinities.throwable,
      effect: [ Effect.none ],
      size: 0.5, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 41, 
      name: "Shuriken", 
      legend: "Les mauvaises langues diront que les ninjas ne savent pas viser.", 
      damage: "D2", 
      feature: "Annule les malus liés au manque d'affinités pour cette arme.", 
      price: 50, 
      type: Affinities.throwable,
      subType: SubAffinities.throwable,
      effect: [ Effect.none ],
      size: 0.5, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 42, 
      name: "Dague à Corde", 
      legend: "Pour ne plus perdre ses affaires.", 
      damage: "D4", 
      feature: "Peut être récupéré via la corde.", 
      price: 45, 
      type: Affinities.throwable,
      subType: SubAffinities.throwable,
      effect: [ Effect.none ],
      size: 0.5, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 43, 
      name: "Bolas", 
      legend: "Une invention sud-américaine bien pratique.", 
      damage: "Aucun", 
      feature: "Ligote la cible à distance.", 
      price: 40, 
      type: Affinities.throwable,
      subType: SubAffinities.throwable,
      effect: [ Effect.none ],
      size: 0.5, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 44, 
      name: "Plumbata", 
      legend: "La version romaine du jeu de fléchette.", 
      damage: "D4", 
      feature: "Inflige un second jet de dégâts à l'extraction.", 
      price: 50, 
      type: Affinities.throwable,
      subType: SubAffinities.throwable,
      effect: [ Effect.none ],
      size: 0.5, 
      fire: false,
      startingWeapon: false,
    ),
    Weapon(
      id: 45, 
      name: "Javelin", 
      legend: "Une arme de chasse ayant l'avantage de préparer les brochettes en avance.", 
      damage: "D6", 
      feature: "Trop gros pour être dissimulable.", 
      price: 80, 
      type: Affinities.throwable,
      subType: SubAffinities.throwable,
      effect: [ Effect.none ],
      size: 0.5, 
      fire: false,
      startingWeapon: false,
    ),

    // Armes de poing 1

    Weapon(
      id: 46, 
      name: "Smith&Wesson Model 2", 
      legend: "L'arme de poing la plus populaires des allées sombre de Londres.", 
      damage: "D2 par balle", 
      feature: "", 
      price: 100, 
      type: Affinities.firearm,
      subType: SubAffinities.smallHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point32Rimfire,
      reload: 2,
      magazineSize: 6,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: true,
    ),
    Weapon(
      id: 47, 
      name: "Howdah-Lancaster Squarebox Pistol", 
      legend: "Pourquoi se limiter à un canon quand on peut en avoir quatre ?", 
      damage: "D4 par balle", 
      feature: "", 
      price: 200, 
      type: Affinities.firearm,
      subType: SubAffinities.smallHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point47Round,
      reload: 4,
      magazineSize: 4,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: true,
    ),
    Weapon(
      id: 48, 
      name: "Colt Single Action Army", 
      legend: "Six balles. Plus qu'il n'en faut pour tuer tout ce qui bouge.", 
      damage: "D4 par balle", 
      feature: "", 
      price: 300, 
      type: Affinities.firearm,
      subType: SubAffinities.smallHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point41LongColt,
      reload: 4,
      magazineSize: 6,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: false,
    ),
    Weapon(
      id: 49, 
      name: "American Rifle Derringer", 
      legend: "La puissance d'un fusil dans un mouchoir de poche.", 
      damage: "D6 par balle", 
      feature: "", 
      price: 500, 
      type: Affinities.firearm,
      subType: SubAffinities.smallHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point40LongRifle,
      reload: 1,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: true,
    ),
    Weapon(
      id: 50, 
      name: "Savage 1861 Navy", 
      legend: "Il a réduit la concurrence en cendres, en son temps.", 
      damage: "D2 par balle", 
      feature: "", 
      price: 750, 
      type: Affinities.firearm,
      subType: SubAffinities.smallHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point36,
      reload: 3,
      magazineSize: 8,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: false,
    ),
    Weapon(
      id: 51, 
      name: "Smith&Wesson Schofield Quickshotter", 
      legend: "Marche aussi bien à Dallas qu'à Whitechapel.", 
      damage: "D2 par balle", 
      feature: "", 
      price: 1500, 
      type: Affinities.firearm,
      subType: SubAffinities.smallHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point32Rimfire,
      reload: 2,
      magazineSize: 6,
      secondMagazine: false,
      firing: Firing.dA,
      startingWeapon: false,
    ),
    Weapon(
      id: 52, 
      name: "Sharps Pepperbox Model 1C", 
      legend: "Quel intérêt d'avoir quatre canons si on ne peut pas tirer avec les quatre en même temps ?", 
      damage: "D2 par balle", 
      feature: "", 
      price: 1200, 
      type: Affinities.firearm,
      subType: SubAffinities.smallHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point22,
      reload: 6,
      magazineSize: 4,
      secondMagazine: false,
      firing: Firing.multiple,
      startingWeapon: false,
    ),
    Weapon(
      id: 53, 
      name: "Volcanic Repeater", 
      legend: "Une légende oublié de l'Ouest Américain. Oubliée, mais efficace.", 
      damage: "D2 par balle", 
      feature: "", 
      price: 1900, 
      type: Affinities.firearm,
      subType: SubAffinities.smallHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point22,
      reload: 6,
      magazineSize: 8,
      secondMagazine: false,
      firing: Firing.dA,
      startingWeapon: false,
    ),
    Weapon(
      id: 54, 
      name: "Goldwin Moonslayer Model 3", 
      legend: "Il a fallu une lance, une épée et une armure à St Michel pour terrasser le dragon. Fort heureusement les temps ont changé.", 
      damage: "D4 par balle", 
      feature: "", 
      price: 2200, 
      type: Affinities.firearm,
      subType: SubAffinities.smallHandgun,
      effect: [ Effect.holy ],
      size: 1, 
      fire: true,
      calibre: Calibre.point41MoonSlayer,
      reload: 3,
      magazineSize: 7,
      secondMagazine: false,
      firing: Firing.dA,
      startingWeapon: false,
    ),
    Weapon(
      id: 55, 
      name: "Starr Model 1869 H1", 
      legend: "Issu de plusieurs années de recherche, le premier revolver destiné à la chasse de nuit.", 
      damage: "D4 par balle Perforant", 
      feature: "", 
      price: 2500, 
      type: Affinities.firearm,
      subType: SubAffinities.smallHandgun,
      effect: [ Effect.piercing ],
      size: 1, 
      fire: true,
      calibre: Calibre.point41Comet,
      reload: 2,
      magazineSize: 6,
      secondMagazine: false,
      firing: Firing.dA,
      startingWeapon: false,
    ),
    Weapon(
      id: 56, 
      name: "C96 Mauser Prototype", 
      legend: "Le chef d’oeuvre du savoir faire allemand.", 
      damage: "D2 par balle", 
      feature: "", 
      price: 4000, 
      type: Affinities.firearm,
      subType: SubAffinities.smallHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point32Rimfire,
      reload: 2,
      magazineSize: 10,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: false,
    ),

    // Armes de poing 2

    Weapon(
      id: 57, 
      name: "Besserschmidt Bucephale 1868", 
      legend: "La puissance d'un étalon en furie derrière la gâchette.", 
      damage: "D4+D2 par tir", 
      feature: "(2 Barillets, 2 balles/tir)", 
      price: 1900, 
      type: Affinities.firearm,
      subType: SubAffinities.bigHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point41and32,
      reload: 6,
      magazineSize: 6,
      secondMagazine: true,
      secondMagazineSize: 6,
      firing: Firing.sA,
      startingWeapon: false,
    ),
    Weapon(
      id: 58, 
      name: "Smith&Wesson Russian Model 03", 
      legend: "Les Russes ont toujours été froid, pragmatique et efficaces. Cela vaut également pour leurs revolvers.", 
      damage: "D4 par balle Perforant", 
      feature: "", 
      price: 2000, 
      type: Affinities.firearm,
      subType: SubAffinities.bigHandgun,
      effect: [ Effect.piercing ],
      size: 1, 
      fire: true,
      calibre: Calibre.point44Magnum,
      reload: 4,
      magazineSize: 8,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: false,
    ),
    Weapon(
      id: 59, 
      name: "Colt Walker Conversion", 
      legend: "Très prisée lors de l’évangélisation des territoires sauvages. Rentre parfaitement dans une bible évidée.", 
      damage: "D6 par balle", 
      feature: "", 
      price: 1600, 
      type: Affinities.firearm,
      subType: SubAffinities.bigHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point45,
      reload: 2,
      magazineSize: 5,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: false,
    ),
    Weapon(
      id: 60, 
      name: "Mars Automatic Pistol", 
      legend: "Le fleuron de l'industrie britannique, un nouveau mécanisme de tir. Plus rapide, plus puissant, on arrête pas le progrès.", 
      damage: "D6 par balle", 
      feature: "", 
      price: 3500, 
      type: Affinities.firearm,
      subType: SubAffinities.bigHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point45,
      reload: 4,
      magazineSize: 8,
      secondMagazine: false,
      firing: Firing.semA,
      startingWeapon: false,
    ),
    Weapon(
      id: 61, 
      name: "Remington 1873 Desperado", 
      legend: "La puissance d'un mustang, la vitesse d'un aigle chauve. La personnification de l'esprit américain.", 
      damage: "D6 par balle", 
      feature: "", 
      price: 1800, 
      type: Affinities.firearm,
      subType: SubAffinities.bigHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point45Remington,
      reload: 2,
      magazineSize: 6,
      secondMagazine: false,
      firing: Firing.dA,
      startingWeapon: false,
    ),
    Weapon(
      id: 62, 
      name: "Colt Walker Ebony", 
      legend: "Il était dit qu'aucun revolver ne pouvait accueillir la nouvelle cartouche de Magnum. Puis Samuel Colt est arrivé.", 
      damage: "D6 par balle", 
      feature: "", 
      price: 2200, 
      type: Affinities.firearm,
      subType: SubAffinities.bigHandgun,
      effect: [ Effect.piercing ],
      size: 1, 
      fire: true,
      calibre: Calibre.point44Magnum,
      reload: 2,
      magazineSize: 6,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: false,
    ),
    Weapon(
      id: 63, 
      name: "Goldwin Colonial Thunder Model H3", 
      legend: "Une arme à la mécanique arrogante et puissante, parfait exemple de l'impérialisme britannique.", 
      damage: "D6 par balle", 
      feature: "2 dégâts confirmés", 
      price: 2800, 
      type: Affinities.firearm,
      subType: SubAffinities.bigHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point454Casul,
      reload: 1,
      magazineSize: 6,
      secondMagazine: false,
      firing: Firing.dA,
      startingWeapon: false,
    ),
    Weapon(
      id: 64, 
      name: "HFR Nightkiller Model H2", 
      legend: "L'arme ayant le meilleur palmarès de la Fondation. On ne compte plus les vampires qui ont subi sa morsure.", 
      damage: "D6 par balle", 
      feature: "3 dégâts confirmés", 
      price: 3000, 
      type: Affinities.firearm,
      subType: SubAffinities.bigHandgun,
      effect: [ Effect.none ],
      size: 1, 
      fire: true,
      calibre: Calibre.point454Casul,
      reload: 2,
      magazineSize: 6,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: false,
    ),

    // Fusil à dispersion

    Weapon(
      id: 65, 
      name: "Tromblon", 
      legend: "Efficace sur les antilopes, les éléphants, les pygmée et les morveux, c'était l'arme de choix de l'Oncle Nestor.", 
      damage: "D6 (<10m) | D2 (<25m)", 
      feature: "", 
      price: 150, 
      type: Affinities.firearm,
      subType: SubAffinities.dispersion,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.bore8,
      reload: 2,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: true,
    ),
    Weapon(
      id: 66, 
      name: "Tromblon à rouet", 
      legend: "Un tromblon, c'est comme un bon chien. C'est pas forcément le plus beau, mais c'est loyal, ça a une bonne tête et ça aboie fort.", 
      damage: "D6 (<15m) | D4 (<25m)", 
      feature: "", 
      price: 250, 
      type: Affinities.firearm,
      subType: SubAffinities.dispersion,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.bore8,
      reload: 2,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: false,
    ),
    Weapon(
      id: 67, 
      name: "Maverick double barreled", 
      legend: "Deux gâchettes, deux chiens, deux canons, une seule arme. Et tout le pragmatisme des fermiers du Kansas.", 
      damage: "D8 (<10m) | D6 par balle", 
      feature: "", 
      price: 500, 
      type: Affinities.firearm,
      subType: SubAffinities.dispersion,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.gauge12,
      reload: 1,
      magazineSize: 2,
      secondMagazine: false,
      firing: Firing.separedTrigger,
      startingWeapon: false,
    ),
    Weapon(
      id: 68, 
      name: "H&Holland Double Rifle", 
      legend: "Initialement prévu pour la chasse au renard, il s'avère très efficace pour celle au sanglier. Et au loup. Pour tout les gibiers en fait.", 
      damage: "D8 (<30m) | D6 par balle", 
      feature: "", 
      price: 600, 
      type: Affinities.firearm,
      subType: SubAffinities.dispersion,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.gauge12,
      reload: 1,
      magazineSize: 2,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: false,
    ),
    Weapon(
      id: 69, 
      name: "Rosario Blunderbuss", 
      legend: "Conçue d'après les plans d'un chasseur de sorcières mexicain, on ne s'attend pas à sa puissance inquisitrice.", 
      damage: "2D4 (<25m) | D6 par balle", 
      feature: "", 
      price: 700, 
      type: Affinities.firearm,
      subType: SubAffinities.dispersion,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.bore8,
      reload: 1,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: false,
    ),
    Weapon(
      id: 70, 
      name: "Spencer Lionheart Sawed off Rifle", 
      legend: "Prenez un fusil de chasse et retirez lui sa précision. Il ne reste que de la puissance brute et explosive. Pile ce qu'il vous faut.", 
      damage: "D8+2 (<30m) | D8 par balle", 
      feature: "", 
      price: 1200, 
      type: Affinities.firearm,
      subType: SubAffinities.dispersion,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.gauge10,
      reload: 1,
      magazineSize: 2,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: false,
    ),
    Weapon(
      id: 71, 
      name: "Besserschmidt M44 Seraph", 
      legend: "Une gâchette pour envoyer tout vos problèmes repeindre la pièce.", 
      damage: "2D4 (<30m) | D8 par balle", 
      feature: "3 dégâts confirmés", 
      price: 1700, 
      type: Affinities.firearm,
      subType: SubAffinities.dispersion,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.gauge12,
      reload: 2,
      magazineSize: 3,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: false,
    ),
    Weapon(
      id: 72, 
      name: "Vetterli Stromboli MK IV", 
      legend: "Éruption de feu et de plomb. La diplomatie Sicilienne.", 
      damage: "D8+3 (<30m) | D8 par balle", 
      feature: "", 
      price: 2500, 
      type: Affinities.firearm,
      subType: SubAffinities.dispersion,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.gauge10,
      reload: 1,
      magazineSize: 5,
      secondMagazine: false,
      firing: Firing.mLev,
      startingWeapon: false,
    ),

    // Fusil 1

    Weapon(
      id: 73, 
      name: "Vetterli M1834", 
      legend: "Apparemment les armes de chasse à coure marche aussi bien sur un vampire que sur un cerf.", 
      damage: "D6 par balle | D4 (>100m)", 
      feature: "", 
      price: 200, 
      type: Affinities.firearm,
      subType: SubAffinities.smallRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point22LR,
      reload: 1,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: true,
    ),
    Weapon(
      id: 74, 
      name: "Snider-Enfield Model 1871", 
      legend: "Le succès de l'armée britannique tient en quelque mot : des hommes disciplinés et un fusil robuste et simple à utiliser.", 
      damage: "D6 par balle", 
      feature: "", 
      price: 500, 
      type: Affinities.firearm,
      subType: SubAffinities.smallRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point51Enfield,
      reload: 1,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.none,
      startingWeapon: false,
    ),
    Weapon(
      id: 75, 
      name: "M-Henry Rifle Mark II", 
      legend: "L'arme qui à assujettit la moitié du monde à la puissance impériale de l’Angleterre victorienne.", 
      damage: "D6 par balle", 
      feature: "", 
      price: 1000, 
      type: Affinities.firearm,
      subType: SubAffinities.smallRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point44Henry,
      reload: 6,
      magazineSize: 10,
      secondMagazine: false,
      firing: Firing.mLev,
      startingWeapon: false,
    ),
    Weapon(
      id: 76, 
      name: "Harker Revolver Rifle Mark IV", 
      legend: "Un mécanisme de revolver sur un fusil. Une arme bâtarde certes, mais redoutablement efficace.", 
      damage: "D6 par balle", 
      feature: "", 
      price: 1500, 
      type: Affinities.firearm,
      subType: SubAffinities.smallRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point41LongColt,
      reload: 2,
      magazineSize: 5,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: false,
    ),
    Weapon(
      id: 77, 
      name: "Winchester R-R Model 1873", 
      legend: "On oublie souvent un détail dans la légende de cet arme mythique : elle est la cause directe de presque tout les fantômes américains.", 
      damage: "D6 par balle", 
      feature: "", 
      price: 1800, 
      type: Affinities.firearm,
      subType: SubAffinities.smallRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point44Winchester,
      reload: 6,
      magazineSize: 12,
      secondMagazine: false,
      firing: Firing.mLev,
      startingWeapon: false,
    ),
    Weapon(
      id: 78, 
      name: "Vetterli M1871 Karabiner", 
      legend: "Un jour un armurier suisse s'est mis en tête de créer une arme capable d'abattre un ours d'une seule balle.", 
      damage: "D8 par balle", 
      feature: "", 
      price: 2500, 
      type: Affinities.firearm,
      subType: SubAffinities.smallRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point38d10v4mm,
      reload: 4,
      magazineSize: 4,
      secondMagazine: false,
      firing: Firing.mVer,
      startingWeapon: false,
    ),
    Weapon(
      id: 79, 
      name: "Paternoster Silversing Spécial", 
      legend: "Une création spéciale des armuriers de la Fondation Hellsing pour la chasse au gros gibier.", 
      damage: "D6+2 par balle", 
      feature: "", 
      price: 2600, 
      type: Affinities.firearm,
      subType: SubAffinities.smallRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point426SilverDevil,
      reload: 1,
      magazineSize: 3,
      secondMagazine: false,
      firing: Firing.mVer,
      startingWeapon: false,
    ),

    // Fusil 2

    Weapon(
      id: 80, 
      name: "Sharps Buffalo Carbine M1874", 
      legend: "Peu probable, mais bon à savoir, cette arme peut arrêter un bison en pleine charge. À condition de tirer à temps bien sur.", 
      damage: "D8 par balle", 
      feature: "", 
      price: 1000, 
      type: Affinities.firearm,
      subType: SubAffinities.bigRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point45Sharps,
      reload: 1,
      magazineSize: 1,
      secondMagazine: false,
      firing: Firing.sA,
      startingWeapon: false,
    ),
    Weapon(
      id: 81, 
      name: "Enfield PR Model 1874", 
      legend: "Conçue par les ingénieurs de l'arsenal royal, cette arme sobre et efficace manque de style, mais pas de précision.", 
      damage: "D8 par balle", 
      feature: "", 
      price: 1500, 
      type: Affinities.firearm,
      subType: SubAffinities.bigRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point57Enfield,
      reload: 2,
      magazineSize: 3,
      secondMagazine: false,
      firing: Firing.mVer,
      startingWeapon: false,
    ),
    Weapon(
      id: 82, 
      name: "Krunka Karabiner Model 1869", 
      legend: "Dans les froides plaines de Pologne, la chasse au loup est au même titre que la vodka, une institution culturelle.", 
      damage: "D8 par balle", 
      feature: "", 
      price: 1800, 
      type: Affinities.firearm,
      subType: SubAffinities.bigRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point52R,
      reload: 2,
      magazineSize: 2,
      secondMagazine: false,
      firing: Firing.separedTrigger, // PAS UN S.A., c'est une erreur d'Hugo
      startingWeapon: false,
    ),
    Weapon(
      id: 83, 
      name: "M84 Marksman", 
      legend: "La ligne parfaite entre le travail artistique d'un armurier de génie et le concentré de toutes les dernières innovations technologiques.", 
      damage: "D8 par balle", 
      feature: "", 
      price: 2000, 
      type: Affinities.firearm,
      subType: SubAffinities.bigRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point52R,
      reload: 4,
      magazineSize: 5,
      secondMagazine: false,
      firing: Firing.mVer,
      startingWeapon: false,
    ),
    Weapon(
      id: 84, 
      name: "Besserschmitt Hellsing Special Meteor", 
      legend: "Un gros calibre, un magasin décent, une mécanique bien huilée, le tout dans une crosse de sorbier. La qualité allemande.", 
      damage: "D8 par balle", 
      feature: "2 dégâts confirmés", 
      price: 3000, 
      type: Affinities.firearm,
      subType: SubAffinities.bigRifle,
      effect: [ Effect.none ],
      size: 2,
      fire: true,
      calibre: Calibre.point56Meteor,
      reload: 3,
      magazineSize: 5,
      secondMagazine: false,
      firing: Firing.mVer,
      startingWeapon: false,
    ),
    Weapon(
      id: 85, 
      name: "J-NS63 Templar", 
      legend: "Parfois, répandre l'amour et la parole du Seigneur nécessite l'usage d'un fusil antimatériel. Ce sont des choses qui arrivent.", 
      damage: "D10 par balle", 
      feature: "", 
      price: 7000, 
      type: Affinities.firearm,
      subType: SubAffinities.bigRifle,
      effect: [ Effect.piercingAggr ],
      size: 2,
      fire: true,
      calibre: Calibre.point66PaterNoster,
      reload: 3,
      magazineSize: 3,
      secondMagazine: false,
      firing: Firing.mVer,
      startingWeapon: false,
    ),
  ];

  ////////////////////////////////////
  //                                //
  // Fonction utiles pour les armes //
  //                                //
  ////////////////////////////////////

  Weapon getWeaponById(int id) {
    Weapon res = allWeapons.last;

    for (var weapon in allWeapons) {
      if (weapon.id == id) {
        res = weapon;
      }
    }

    return res;
  }

  List<Weapon> getWeaponListBySubtype(SubAffinities subType) {
    List<Weapon> res = [];

    for (var weapon in allWeapons) {
      if (weapon.subType == subType) {
        res.add(weapon);
      }
    }

    return res;
  }

  Weapon getWeaponByName(String name) {
    Weapon res = allWeapons.last;

    for (var weapon in allWeapons) {
      if (weapon.name == name) {
        res = weapon;
      }
    }

    return res;
  }

  int getLastWeaponId() {
    int res = allWeapons.last.id;

    return res;
  }
}
